### ISSUE TITLE
SIGILL in builtins? with incremental GC

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1229]
# TODO
- [ ] figure out how to run gctest in bdwgc
- [ ] build & run with NO_SOFT_VDB, which should work. If it does, it means problem is with SOFT_VDB!?
- [ ] build & run with NO_VDB_FOR_STATIC_ROOTS, if it works, this is where the problem is..

# Description

I've enabled the incremental GC and when running our test suite a lot of test programs die with SIGILL or SIGSEGV. I don't understand why but it appears to be a combination of GC, incremental GC support, like size of the program or something like that (possibly timing related?) and part of what the program actually does. For example, by varying the number of RTS worker threads I can get a program to crash or not crash. We malloc some stuff for the threads and GC is triggered indirectly via malloc, so maybe we now trigger gc at "the wrong time"? 

At least two of the failures I see are SIGILL happening in builtin functions, I think. For example the test_re program, which dies trying to do a _ge_ comparison. How can this be an illegal instruction? What is being called under the hood here?
```
Core was generated by `out/rel/bin/test_re --rts-wthreads=1'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00000000003e1057 in reQ_matches (pattern=0x7f27fd8687c0, string=0x7f27fd8687a0) at foobar/out/types/re.c:61
61	        if (((B_bool (*) (B_Ord, B_int, B_int))reQ_W_125->$class->__ge__)(reQ_W_125, pos, str_len)->val) {
[Current thread is 1 (Thread 0x7f27fd8576c0 (LWP 2217557))]
(gdb) bt
#0  0x00000000003e1057 in reQ_matches (pattern=0x7f27fd8687c0, string=0x7f27fd8687a0) at foobar/out/types/re.c:61
#1  0x00000000003b731b in test_reQ_L_7C_13cont (W_692=0x7f27fd870e10, W_618=0x7f27fd868e60, W_454=0x7f27fd870e70, W_547=0x7f27fd871f90, self=0x7f27fd874ee0, C_cont=0x438f68 <$Done$instance>, env=0x7f27fd874f50, C_14res=0x0) at foobar/out/types/test_re.c:512
#2  0x00000000003b8f9f in test_reQ_L_27ContD___call__ (L_self=0x7f27fd86ceb0, G_1=0x0) at foobar/out/types/test_re.c:593
#3  0x00000000002c6361 in wt_work_cb (ev=<optimized out>) at rts/rts.c:1530
#4  0x00000000003764df in uv__run_check (loop=0x7f27fd86b800) at src/unix/loop-watcher.c:67
#5  0x0000000000366862 in uv_run (loop=0x7f27fd86b800, mode=UV_RUN_DEFAULT) at src/unix/core.c:420
#6  0x00000000002c6aef in main_loop (idx=<optimized out>) at rts/rts.c:1695
#7  0x00000000003ac902 in GC_pthread_start_inner (sb=sb@entry=0x7f27fd856e78, arg=arg@entry=0x7ffe0bfc03f8) at pthread_start.c:55
#8  0x00000000003aa2ac in GC_pthread_start (arg=0x7ffe0bfc03f8) at pthread_support.c:2177
#9  0x00007f27fd927fd4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#10 0x00007f27fd9a85ac in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```

@sydow I wonder if you have an idea about what's going on and can take a look at this? There is a `gc-incremental` branch where I have enabled the incremental GC, simply pull that, build acton and then do `make test` and I'm sure you will see a bunch of test apps failing, pick any to debug.

It might be useful to copy the program into an acton project instead of compiling it in place, since then you are able to more easily change the C code, for example:
- `actonc new gc-debug`
- `cd gc-debug`
- `rm src/*`
- `cp $ACTON_REPO/test/stdlib_auto/test_re.act src`
- `actonc build`
- generated C code is now in out/types/test_re.c, insert debug code etc
- `./build.sh` to build C code (but not regenerate from .act -> .c)
- try running...
sorry if I'm being captain obvious

**Comment by sydow** [comment]
On 31 Mar 2023, at 12:55, Kristian Larsson ***@***.***> wrote:
> 
> @sydow I wonder if you have an idea about what's going on and can take a look at this? There is a gc-incremental branch where I have enabled the incremental GC, simply pull that, build acton and then do make test and I'm sure you will see a bunch of test apps failing, pick any to debug.
> 
> 

I just did this, but unfortunately (well,…) the test suite passed. I did exactly what you suggested:

git pull
git checkout gc-incremental
make
make test

I don’t see what I can do now, so I am leaving this for the moment…

Björn

**Comment by plajjan** [comment]
@sydow Interesting that it passes for you! You are on a mac, right? The new one with M1/M2 CPU?

**Comment by sydow** [comment]
Yes, MacBook Air M1, 2020. MacOS 12.5.1.

**Comment by plajjan** [comment]
I've tested more and setting NO_VDB_FOR_STATIC_ROOTS fixes this problem, so there seems to be a bug in bdwgc for using VDB to detect references in the static roots. I'm not sure what the consequences of enabling NO_VDB_FOR_STATIC_ROOTS is, like does that mean static roots is always scanned? Or not? It's static, so should only need to be scanned once?

We should close this issue and open another for continuing the work on using incremental GC.

**Comment by plajjan** [comment]
I think we should give up on incremental with the BDWGC. Better looking into MPS GC #2322. Closing.
