### ISSUE TITLE
The plan for C compilation

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1253]
## TODO
- [x] move libActonDeps to arch dependent file path, like `libActonDeps-linux-x86_64.a`
- [x] upload `libActonDeps-$(PLATFORM).a` as artifact in release
- [x] move deps- release to actonlang/libactondeps
- [x] move libactongc to platform dependent file path
- [x] upload libactongc too!
- [x] also upload header files, baking all libs & headers into one tar ball
- [x] include DEPS_SUM in tar ball name!
- [x] add support to `Makefile` to download tar ball from actonlang/libactondeps
  - [x] variable to force local build
  - [x] save DEPS_SUM of downloaded files (libActonDeps + headers + libactongc) so we know when to download new file!
  - [x] airplane safe, i.e. do not rely on curl to redownload the file for up-to-date check
- [x] verify header files are platform independent in deps archives from like macos & linux
  - [ ] headers differ slightly, `../linux/include/bsdnt/nn_linear_arch.h` on macos includes `#include "arch/inline/nn_linear_x86_64_core2.h"`
- [ ] automatically add deps- git tag on main branch
- [ ] produce single deps archive that combines libActonsDeps from all platforms
- [x] do acton project builds using build.zig style
  - [x] call it project-build.zig and place it in acton dist
  - [ ] #1616
  - [x] for actonc single file compilation, we copy output binary from temp project to final destination file
  - [x] change paths passed from actonc to `build.zig` to be absolute
    - [x] reduce path mangling in `build.zig`
  - [x] do one-shot build, by finding all .root.c files and building binaries from them
    - [x] do not run `zig build` multiple times from actonc
  - [x] precompile our `project-build.zig` (during acton system dist build) and ship ready-to-run binary, this way we don't need to think about cache or whatnot
    - [x] implies we don't run `zig build` but rather "the next step" of what zig does internally
  - [x] use acton project local zig-cache dir, maybe rename as to not expose zig as clearly? `build-cache`? zig is no secret but it might be more confusing
- [x] stop materializing libActonProject.a, at least as a test
- [x] allow customization through project specific build.zig
  - [x] replace stdlib Makefile with custom build.zig
  - [x] get rid of custom Makefile builds
- [x] build libActonDeps with zig
  - [x] libbsd - removed
  - [x] libmd - removed
  - [x] argp-standalone
  - [x] bsdnt
  - [x] pcre2
  - [x] protobuf-c
  - [x] libutf8proc
  - [x] libuuid
  - [x] libuv
  - [x] libxml2
  - [x] libnetstring
  - [x] libyyjson
- [x] add libActonDB as zig project dependency
  - that is, avoid creating libActonDB.a
- [x] add libActon as zig project dependency
- [ ] manage / clean up the cache, mostly outsource to zig?

## Description
I've been pondering this for a bit, there's a couple of different topics, like build caching and cross-compilation, that are somewhat intertwined and I think we could get some really cool results if we do this right.

So, zig has its builtin build system, instead of using Makefile you define a build.zig which in itself is just a zig program that gets compiled and then run when you issue `zig build`. It uses a particular module from the zig stdlib, called Build which sort of supports Makefile-concepts, though it's a little less declarative and a little more imperative. It looks pretty good though and supports things that certainly are not in Make, like a very good up-to-date check for files (its harder than it seems) and I think it can automatically parse C files and chase down includes so one doesn't have to repeat all dependencies in the Makefile (since they're already in the C source). Also, we are currently using `zig cc` as a drop-in cc replacement. It's a low level interface and doesn't sport all these cool features, so converting to using zigs higher level interface, like build.zig, would enable this. Based on some testing in #1249, the caching etc seems to work and significantly reduces the time it takes to do nothing (because we use the cache). Most promising. The one annoying thing is that building build.zig into an actual application is slow, like ~5 seconds slow or so, but this is only done once for as long as there are new modules added to a project, or removed.

zig has really good support for cross-compilation, so that's also something that should be easier to do once we convert over to build.zig

Today we allow custom build stuff by defining a Makefile in an Acton project. Most notably, we are using this in stdlib. We can in fact not replace this straight up with an automatically generated build.zig since it just doesn't know how to properly compile some of our modules.

We could move compilation of stuff to when the user actually wants it. Like instead of building libActon during the build of the Acton distribution, we could just ship the source code and the end user would get the stuff in libActon (builtins, RTS & stdlib) in source form and compile it while building their Acton project. If we do caching right, this shouldn't cost us much extra. There's a big benefit in that it would become possible to inject compilation flags and options. We can only reasonable ship one or two variations, like we have dev and release mode, so libActon is compiled twice. If we are now doing cross-compilation, we have 3 platforms and two variations for a total of 6 combinations. Add another compilation option and you quickly end up with an unrealistically long list of combinations. Compiling from source enables end user to influence compilation of builtins etc much more.

- [ ] support customizing builds in an Acton project
  - I see two main alternatives:
    - entirely custom build.zig
      - painful since it also means manually updating list of source files etc, but could maybe be a stop-gap solution?
    - somehow injecting stuff into a generated build.zig
- [ ] having cross-compiled versions of all library archives
  - libActonDeps
    - cross-compilation is the holy grail!
    - seems very hard to actually cross-compile since all the projects are built using classic automake etc infrastructure (no build.zig), so we are reliant on that working properly and it just doesn't seem too?
    - one alternative is to write build.zig for all our external dependencies, so we could cross-compile?
    - the more direct and pragmatic approach is to compile libActonDeps on each platform and then collect all the actual archives and add to the distribution, i.e. we compile on x86_64-macos and aarch64-macos, x86_64-linux, then collect those three libActonDeps and place in the distribution for all three platforms
      - this would run in CI and would be "impossible" to do locally
        - well, if you have all computers available to you, you could of course do it... but yeah, not very simple
  - libactongc
    - prolly same approach as for libActonDeps, not sure if we can cross-compile bdwgc
  - libActon
    - this includes builtins, RTS and stdlib
    - should be able to build using a build.zig
    - do we really need to build this at all? can we bundle it as source and compile when compiling an acton project, this way we can use whatever compilation flags we want and don't need to prebundle X number of variations, rather leaving it to be compiled in some specific way when the user needs that variation
      - it's not reasonable to bundle many many variations, so we are effectively limited in how many 
  - libActonDB
    - our DB stuff, should be able to build using a build.zig
- [ ] stop building libActonProject, rather just feeding all the source files to zig directly in build.zig, which simplifies this step a bit
- [ ] use acton project as zig prefix and write bins to prefix/bin for example
    - given direction we are going in means we move from simple compiler profile dev/rel to allow arbitrary stuff to be exposed
    - internally the zig-cache will figure out what build artifacts to use, so we don't have to think about it (like current out/rel vs out/dev)
    - we only need to expose binaries to the user, and we have a choice
      - either produce something on local file system that reflects all compile options that went into it. This is ~impossible, so let's not do it
      - just produce latest file asked for, like bin/hello and if user reruns actonc but with --dev or other compile option, bin/hello is now replaced with the new file
        - they are copied from the zig-cache, so it will be very fast and we won't do actual recompilation

**Comment by plajjan** [comment]
Ok I've misunderstood the caching. We get caching with `zig cc` too, it is stored in `~/.cache/zig` or in zig-cache in the local dir... so that's not a benefit, although I'm pretty sure that I've seen speedups. need to be investigated more! Perhaps there is some other interaction going on...

**Comment by plajjan** [comment]
Separated out #1616 into separate issue. All the other items in here are done or no longer relevant, so closing this!
