### ISSUE TITLE
NG plan for Zig / C build / build.zig

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1724]
- [x] reduce data sent between `actonc` and `builder`
  - this was due to ease of joining paths in Haskell vs Zig
  - but just get on with it, write a function in Zig to join paths and compute more paths in Zig
- [x] add builder flag for only compiling library part (not executable binaries) which is the relevant stuff when used as a dependency
- [x] get rid of prebuilt libActon - always build from source
- [x] use user global zig cache, e.g. `~/.cache/acton/...`
- [x] add cache cleaning functionality into `acton`
  - let cache grow up to X bytes (maybe hard coded for now!?)
  - preferably cleaning only old files periodically, like LRU
  - but if it somehow interferes with zig cache then we'll just have to wipe whole cache when it reaches the maximum allowable size
- [ ] ~~have separate caches for Acton base and Acton projects~~
  - not sure this is possible with Zig today? there is some support for overriding stuff, but still, can we achieve this?
- [x] get rid of `out/` rel / dev, if we always build from sources we won't have prebuilt libraries so it is not necessary to have rel or dev. Output just goes in `out/`. So it'll be like `out/lib/libActonProject.a` and `out/bin/foo`
- [x] add acton(c) option to skip C compilation
- [x] skip C compilation when building base for Acton distribution
- [x] stop include of library archives of external library dependencies, like libuv, as part of distribution, #1871
- [x] avoid building external library dependencies at distribution build time since we don't need them, only build what is necessary for actondb and preferably out-of-tree (hard with includes!?) #1871 
- [ ] ~~can we clear out the oldest stuff from the cache rather than everything? LRU style?~~ #1603 https://github.com/ziglang/zig/issues/15358
- [x] support inclusion of external libraries

**Comment by plajjan** [comment]
All done here, closing.
