### ISSUE TITLE
Rework zig cache - do not empty automatically

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#1858]
I added the clearing of our zig build cache since I didn't want unbounded growth. However, the cache is in fact used not just used for caching of built artifacts, zig also uses it for downloaded dependencies. Zig actually has two caches, a global cache where downloads are placed and the "cache" (implied to be local then)? At the time we started doing zig builds, there wasn't a difference as zig didn't have a package manager, so I just placed the global and local cache in the same dir ~/.cache/acton, but I think we should separate the two. The global cache should not be automatically cleared at all, maybe a warning about reaching a certain size, but also not repeating the warning all the time, so maybe remember warning threshold and bump it up, so warn over 10GB and then for every addition 1GB in size or so?

The local cache can be cleared automatically like we do today!

## TODO
- [x] split cache / gcache
- [x] automatically clear local cache
- [x] warn on gcache size
- [x] warn on gcache size in increments of X
