### ISSUE TITLE
Replace env arg with env modules + token

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#291]
To concretize, let's do network related stuff as a an example:

The env object passed in contains argv and a root authentication token

```

# net module

# specialized auth token for doing TCP connect
class TCPConnectAuth:
    pass

actor TCPConnection():
    close: action()

def connect(auth : TCPConnectAuth, host : str, port : net.port, on_connect : Action(Connection))

```

An Acton program that listens to TCP:
```python
actor main(env):
    def connect_handler(conn):
        print("Got a connection, yay")

    net.connect(TCPConnectAuth(env.root_auth), "www.google.com", 80, connect_handler)
```

# Questions
- should WorldAuth token be a new argument to the root actor or an attribute of `env`?
  - I think env is going away, all functions like listen & connect will move to modules, only remaining things is args?
  - do we keep `env` for `env.argv`?
  - do we replace `env` with just `argv` directly? so `actor main(world_auth, argv)` ??

# TODO
- [x] create WorldAuth token type that is not possible to instantiate
- [x] RTS should create WorldAuth instance and feed into root actor
- [ ] how to create union of types? TCPAuth should take WorldAuth or NetAuth as input token

**Comment by plajjan** [comment]
@nordlander what should `world` be? Like is it a class or some more primitive thing?

**Comment by nordlander** [comment]
Yep, a primitive type is essentially just a built-in class with no methods or attributes and no relation to any other type. I can add this part to the compiler.

What do we want to call it? World, world, WORLD? Or something else?

-- Johan

**Comment by plajjan** [comment]
I think it should be called WorldAuth. We can use this Auth suffix on all these auth tokens. We'll have more specialized tokens once we start using this, like for doing TCP connect I imagine:

```
WorldAuth -> NetAuth -> TCPAuth -> TCPConnect
```

How can we write a class type that is also not a constructor? Or do we just leave that "hole" for the time being and fix later?

**Comment by plajjan** [comment]
And how do I write a union of types?

The function net.connect() should take the TCPConnectAuth as arg. To create a TCPConnectAuth I need a token of any of the "higher" types. Should we use inheritance for this? How do we write a class that requires an auth token to instantiate? I guess we can't?

I think we need functions that take the right token and create a new token of the right type?

**Comment by nordlander** [comment]
Yes, I think inheritance would fit the bill. I've pushed some fixes to make it possible to both define abstract classes without constructors (just leave out the __init__ method) and inherit from them (in which case one could demand that the subclass constructor takes a value of the parent class).

The exact design of such a hierarchy should perhaps be discussed some more, but at least we now have the means to define hierrarchies that involve abstract classes.

**Comment by plajjan** [comment]
@nordlander how do I write a union of types?

In this auth hierarchy:
```
WorldAuth -> NetAuth -> TCPAuth -> TCPConnect
```
NetAuth is level 2 and requires WorldAuth but for TCPAuth I should be able to pass in WorldAuth or NetAuth, so I imagine I need to write the required type as a union. How do I do that? Is it possible today?

**Comment by plajjan** [comment]
This is effectively done. We don't have unions of types so we require the full chain, like `net.TCPConnectAuth(net.TCPAuth(net.NetAuth(env.auth))))`. A little cumbersome but it works!

**Comment by nordlander** [comment]
An issue to be returned to in due time, though. MyPy already supports the union notation `WorldAuth | NetAuth`, and we do as well if we restrict the component types to built-in atoms or literals (for constructing enums). I believe supporting the general case should be our long-term goal too.

Logically it isn't hard to define what union types actually mean. Unfortunately, type inference for union types becomes incredibly tricky in the general case. So I'm playing with the idea of stratifying the type system so that union types can be _checked_ but never _inferred_, meaning that a union must be expressed in an explicit signature in order to considered at all. Perhaps this is a good compromise.

To be continued...

**Comment by plajjan** [comment]
Yes, checked but not inferred sounds like a good idea. I mean, inferring union types just sounds like giving up on types... every value would be allowed everywhere and you end up with dynamic language style a la `if isinstance` or `if a is not None and a ...` nonsense.

**Comment by plajjan** [comment]
Ok, I opened #850 for the checked but not inferred union types!
