### ISSUE TITLE
Investigate RTS DDB segfault problems on MacOS

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#523]
So through a pretty unfortunate combination of events it appears we haven't been testing RTS DDB mode properly and that has hidden some form of criticial bug on MacOS such that the RTS appears to segfault when used with the database. I don't have a full grasp on it other than it preventing #518 from passing CI and I've seen failures locally.

## Test failure analysis

Why didn't our testing reveal this?

- CI test_db.py did not correctly report errors
  - because @plajjan wrote fancy `--repeat` functionality around `unittest.main()` and misunderstood the interface, thus hiding errors
  - there is no error handling in RTS, so if the database is dead, we can still effectively continue working. I think the DB does need to up be initially up, but if it dies, then RTS will happily continue. This is known. First implementation simply does not attempt to handle errors. #196 to track.
  - no one manually inspected the build / test output in CI (I mean, who does that anyway?)
- I do essentially all development on Linux, so haven't noticed problems
- I assume @nordlander, who develops on MacOS, does not test much with RTS + DDB, so he doesn't notice...

I fixed the test_db.py error passing in #518 but it is failing since most test runs on MacOS do not work.

## TODO
- [ ] nail down which test is failing. all using the database or is it one in particular?
- [ ] maybe try to get rough failure rate
- [ ] can we improve test harness to tell us about segfaults, right now we just see the whole test failing, not specifically that it is a segfault

**Comment by plajjan** [comment]
I can reproduce this locally on my macbook pro, some findings:
- appears to happen regardless of app; I've tested both the TCP recovery app and our basic app and they fail in similar ways
- it appears we do not see the segfault return code due to timing issue
  - the core file ends up at a whopping 3.5GB, which takes some time to write to disk (I assume)
  - the test script does a `.poll()` and tries to inspect the returncode but since the app is still running, well, at least the process ID is there while I expect it to be interrupted and the kernel is busy writing the core file

**Comment by plajjan** [comment]
So I've collected a bunch of core files and looked at the backtrace, which always states the same thing:
```
➜  test git:(fix-test-db) ✗ lldb -c core.91791 test_db_app
(lldb) target create "test_db_app" --core "core.91791"
Core file '/Users/kll/terastream/acton-mbp/test/core.91791' (x86_64) was loaded.

(lldb) bt
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00007ff809d3f20a libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x00007ff809d7bc8d libsystem_pthread.dylib`_pthread_join + 362
    frame #2: 0x00000001096b64c8 test_db_app`main(argc=8, argv=0x00007ff7b6886900) at rts.c:1931:9
    frame #3: 0x00000001135b04fe dyld`start + 462
(lldb)
```

why are we getting a SIGSTOP?

Since pthread_join is being called, I figured maybe there is a problem with our use of pthread_join, like have we passed it an invalid thread id that's actually just some garbage? I tried replacing the join with a usleep() but I just get a similar backtrace:

```
➜  test git:(fix-test-db) ✗ lldb -c core.89889 rts/ddb_test_server
(lldb) target create "rts/ddb_test_server" --core "core.89889"
Core file '/Users/kll/terastream/acton-mbp/test/core.89889' (x86_64) was loaded.

(lldb) bt
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00007ff809d403da libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007ff809c558a9 libsystem_c.dylib`nanosleep + 196
    frame #2: 0x00007ff809c557df libsystem_c.dylib`usleep + 53
    frame #3: 0x000000010f9e34c8 ddb_test_server`main(argc=11, argv=0x00007ff7b0559888) at rts.c:1928:9
    frame #4: 0x000000011ac094fe dyld`start + 462
(lldb) ^D
```

so I don't think it has anything to do with how we call pthread_join. BTW, this is the pthread_join() for the first worker thread, so I don't see how it could be invalid either...

I've implemented some simple make targets to start the DB instead of test_db.py, just to rule that out as well... no difference, same segfaults.

**Comment by plajjan** [comment]
Starting to realize lldb does not act same way as gdb, I think. I'm no gdb pro either, but when I've had it print a backtrace for me after a core dump, it does so for the thread that caused the seg fault. I'm starting to think that lldb does not.

I built a simple experiment with a simple C program that deliberately seg faults:
```c
int main(int argc, char **argv) {
	*(int *)0 = 0;
	return 0;
}
```
On Linux with gdb:
```
kll@Boxy:~$ cc -g foo.c
kll@Boxy:~$ ./a.out
Segmentation fault (core dumped)
kll@Boxy:~$ gdb a.out core
...
Reading symbols from a.out...
[New LWP 708680]

warning: Section `.reg-xstate/708680' in core file too small.
Core was generated by `./a.out'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/708680' in core file too small.
#0  main (argc=1, argv=0x7ffccaffda18) at foo.c:2
2		*(int *)0 = 0;
(gdb) 
```

In LLDB, it shows up as a SIGSTOP, which is just weird IMHO:
```
```

**Comment by plajjan** [comment]
https://developer.apple.com/library/archive/technotes/tn2124/_index.html#//apple_ref/doc/uid/DTS10003391-CH1-SECCOREDUMPS notes that core dumps are large, but says 451MB where mine are 3.5GB. It's just insane for an application that does nothing!

**Comment by plajjan** [comment]
I've captured a few core files now from running the TCP recovery app test on Mac and they all show the exact same thread state:
```
(lldb) bt all
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x libsystem_pthread.dylib`_pthread_join + 362
    frame #2: 0x ddb_test_server`main(argc=11, argv=0x00007ff7bb721888) at rts.c:1931:9
    frame #3: 0x dyld`start + 462
  thread #2, stop reason = signal SIGSTOP
    frame #0: 0x libsystem_kernel.dylib`__select + 10
    frame #1: 0x ddb_test_server`comm_thread_loop + 926
    frame #2: 0x libsystem_pthread.dylib`_pthread_start + 125
    frame #3: 0x libsystem_pthread.dylib`thread_start + 15
  thread #3, stop reason = signal SIGSTOP
    frame #0: 0x libsystem_kernel.dylib`kevent + 10
    frame #1: 0x ddb_test_server`EVENT_wait(ev=0x000070000a1daf88, timeout=0x0000000000000000) at env.c:58:12
    frame #2: 0x ddb_test_server`$eventloop(arg=0x0000000000000000) at env.c:1263:22
    frame #3: 0x libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x libsystem_pthread.dylib`thread_start + 15
  thread #4, stop reason = signal SIGSTOP
    frame #0: 0x ddb_test_server`$step_serialize(self=0x0000003939353831, state=0x0000600001d5c2d0) at serialize.c:87:20
    frame #1: 0x ddb_test_server`ddb_test_server$$Tester$__serialize__(self=0x0000600002150120, state=0x0000600001d5c2d0) at ddb_test_server.c:714:5
    frame #2: 0x ddb_test_server`$glob_serialize(self=0x0000600002150120, globmap=(ddb_test_server`try_globkey at rts.c:1059)) at serialize.c:203:3
    frame #3: 0x ddb_test_server`serialize_actor(a=0x0000600002150120, txnid=0x0000600001d5c1e0) at rts.c:1117:16
    frame #4: 0x ddb_test_server`main_loop(idx=0x0000000000000001) at rts.c:1268:25
    frame #5: 0x libsystem_pthread.dylib`_pthread_start + 125
    frame #6: 0x libsystem_pthread.dylib`thread_start + 15
  thread #5, stop reason = signal SIGSTOP
    frame #0: 0x libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x libsystem_pthread.dylib`_pthread_cond_wait + 1224
    frame #2: 0x ddb_test_server`main_loop(idx=0x0000000000000002) at rts.c:1321:13
    frame #3: 0x libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x libsystem_pthread.dylib`thread_start + 15
  thread #6, stop reason = signal SIGSTOP
    frame #0: 0x libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x libsystem_pthread.dylib`_pthread_cond_wait + 1224
    frame #2: 0x ddb_test_server`main_loop(idx=0x0000000000000003) at rts.c:1321:13
    frame #3: 0x libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x libsystem_pthread.dylib`thread_start + 15
  thread #7, stop reason = signal SIGSTOP
    frame #0: 0x libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x libsystem_pthread.dylib`_pthread_cond_wait + 1224
    frame #2: 0x ddb_test_server`main_loop(idx=0x0000000000000004) at rts.c:1321:13
    frame #3: 0x libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x libsystem_pthread.dylib`thread_start + 15
```

I removed memory addresses for simpler diffing.

The TCP recovery app (rts/ddb_test_server) crashes very frequently for me. The test_db_app test does not crash nearly as frequently, so I'm focusing on the TCP recovery one for now.

The idle threads in pthread_cond_wait are likely not it... the eventloop is doing EVENT_wait and one worker thread is serializing an actor. Just out of a timing perspective, EVENT_wait will hang for longer periods of time (when there is no I/O) whereas the serialization process should be really fast. Given that we always see the same serialization in the core files might be a smoking gun...

To reduce the likelihood that it's the EVENT_wait I simply added a usleep() in there and lo and behold, the trace instead shows that that thread is spending time sleeping:
```
(lldb) bt all
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00007ff809d3f20a libsystem_kernel.dylib`__ulock_wait + 10
    frame #1: 0x00007ff809d7bc8d libsystem_pthread.dylib`_pthread_join + 362
    frame #2: 0x000000010438e358 ddb_test_server`main(argc=11, argv=0x00007ff7bbbae888) at rts.c:1931:9
    frame #3: 0x000000010d3744fe dyld`start + 462
  thread #2, stop reason = signal SIGSTOP
    frame #0: 0x00007ff809d45e4a libsystem_kernel.dylib`__select + 10
    frame #1: 0x00000001043f0e1e ddb_test_server`comm_thread_loop + 926
    frame #2: 0x00007ff809d7a514 libsystem_pthread.dylib`_pthread_start + 125
    frame #3: 0x00007ff809d7602f libsystem_pthread.dylib`thread_start + 15
  thread #3, stop reason = signal SIGSTOP
    frame #0: 0x00007ff809d403da libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007ff809c558a9 libsystem_c.dylib`nanosleep + 196
    frame #2: 0x00007ff809c557df libsystem_c.dylib`usleep + 53
    frame #3: 0x000000010437589a ddb_test_server`EVENT_wait(ev=0x00007000036bcf88, timeout=0x0000000000000000) at env.c:58:5
    frame #4: 0x0000000104379d37 ddb_test_server`$eventloop(arg=0x0000000000000000) at env.c:1265:22
    frame #5: 0x00007ff809d7a514 libsystem_pthread.dylib`_pthread_start + 125
    frame #6: 0x00007ff809d7602f libsystem_pthread.dylib`thread_start + 15
  thread #4, stop reason = signal SIGSTOP
    frame #0: 0x0000000000000002
    frame #1: 0x0000000104358675 ddb_test_server`$step_serialize(self=0x00006000035fc210, state=0x00006000039f02d0) at serialize.c:102:9
    frame #2: 0x0000000104356060 ddb_test_server`ddb_test_server$$main$__serialize__(self=0x00006000013f4180, state=0x00006000039f02d0) at ddb_test_server.c:754:5
    frame #3: 0x0000000104372510 ddb_test_server`$glob_serialize(self=0x00006000013f4180, globmap=(ddb_test_server`try_globkey at rts.c:1059)) at serialize.c:203:3
    frame #4: 0x000000010437d706 ddb_test_server`serialize_actor(a=0x00006000013f4180, txnid=0x00006000039f80f0) at rts.c:1117:16
    frame #5: 0x000000010437e2a3 ddb_test_server`main_loop(idx=0x0000000000000001) at rts.c:1268:25
    frame #6: 0x00007ff809d7a514 libsystem_pthread.dylib`_pthread_start + 125
    frame #7: 0x00007ff809d7602f libsystem_pthread.dylib`thread_start + 15
  thread #5, stop reason = signal SIGSTOP
    frame #0: 0x00007ff809d40506 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007ff809d7aa89 libsystem_pthread.dylib`_pthread_cond_wait + 1224
    frame #2: 0x000000010437e846 ddb_test_server`main_loop(idx=0x0000000000000002) at rts.c:1321:13
    frame #3: 0x00007ff809d7a514 libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x00007ff809d7602f libsystem_pthread.dylib`thread_start + 15
  thread #6, stop reason = signal SIGSTOP
    frame #0: 0x00007ff809d40506 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007ff809d7aa89 libsystem_pthread.dylib`_pthread_cond_wait + 1224
    frame #2: 0x000000010437e846 ddb_test_server`main_loop(idx=0x0000000000000003) at rts.c:1321:13
    frame #3: 0x00007ff809d7a514 libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x00007ff809d7602f libsystem_pthread.dylib`thread_start + 15
  thread #7, stop reason = signal SIGSTOP
    frame #0: 0x00007ff809d40506 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007ff809d7aa89 libsystem_pthread.dylib`_pthread_cond_wait + 1224
    frame #2: 0x000000010437e846 ddb_test_server`main_loop(idx=0x0000000000000004) at rts.c:1321:13
    frame #3: 0x00007ff809d7a514 libsystem_pthread.dylib`_pthread_start + 125
    frame #4: 0x00007ff809d7602f libsystem_pthread.dylib`thread_start + 15
(lldb)
```

and so the suspicion that there is something funky with serialization grows. Also, we are only seeing segfaults when using the database, so this observation would align with that...

**Comment by plajjan** [comment]
I've added a bunch of print statements to try and nail this down. As far as I can tell, it appears that the crash typically happens in the serialiation of the root actor when it is trying to get the class_id.

for example, for extra avoidance of weird coincidence I added sleeps in step_Serialize:
```c
void $step_serialize($WORD self, $Serial$state state) {                         │
+  87 │ printf("-- step_serialize\n"); fflush(stdout);                                │
+  88 │ printf("  self: %p  state: %p\n", self, state); fflush(stdout);               │
   89 │ if (self) {                                                                   │
+  90 │ │ printf("  -- step_serialize self\n"); fflush(stdout);                       │
+  91 │ │ printf("     self: %p\n", (($Serializable)self));                           │
+  92 │ │ printf("     class: %p\n", (($Serializable)self)->$class);                  │
+  93 │ │ usleep(10000);                                                              │
+  94 │ │ printf("     3...\n"); fflush(stdout);                                      │
+  95 │ │ usleep(10000);                                                              │
+  96 │ │ printf("     2...\n"); fflush(stdout);                                      │
+  97 │ │ usleep(10000);                                                              │
+  98 │ │ printf("     1...\n"); fflush(stdout);                                      │
+  99 │ │ usleep(100);                                                                │
+ 100 │ │ printf("     now...\n"); fflush(stdout);                                    │
+ 101 │ │ printf("     class_id: %p\n", (($Serializable)self)->$class->$class_id);    │
  102 │ │ int class_id = $GET_CLASSID((($Serializable)self)->$class);                 │
+ 103 │ │ printf("     got class_id: %d\n", class_id)
```

and in the output I see:
```
 #RTS# #### Serializing Actor -12
 -- step_serialize
   self: 0x0  state: 0x60000275c030
   - add_header()
 -- step_serialize
   self: 0x0  state: 0x60000275c030
   - add_header()
 -- step_serialize
   self: 0x600003c58300  state: 0x60000275c030
   -- step_serialize self
      self: 0x600003c58300
      class: 0x858501538300
      3...
      2...
      1...
      now...
 E
 ======================================================================
 ERROR: test_app_tcp_recovery (__main__.TestDbAp
```

and this scenario happens most of the time. So why can't we get class_id?

**Comment by plajjan** [comment]
More testing, okay, so I think I've nailed this down. We are serializing an actor which has attributes that have not yet been initialized.

For example, if we set an actor variable attribute to return value of foo(), the compiler will render a continuation to set the actual value. However, we still do need to serialize the actor after the first __init__ which means we will serialize an unset value.

I think the compiler MUST always set all attributes in __init__.

**Comment by nordlander** [comment]
This is indeed true, and a blatant oversight on my part. Good job tracking it down!

So the question is then what to do about it. We cannot avoid the case where continuation-passing occurs halfway through an actor's initialization code (unless we severely restrict the kind of expressions that can be used as initializers -- not an option!). And continuation-passing will often lead to checkpointing against the database, especially since we've started translatin actor construction in terms of a fully-fledged synchronous message. What we seem to need is a way to null out yet uninitialized actor state variables in those cases. I only need to find a good place to do that in the compiler, that doesn't introduce internal type inconsistencies...

**Comment by plajjan** [comment]
I've created #525 to track the particular problem of initializing or zeroising all actor attributes before serialization.

Meanwhile I will try to rewrite the test applications to avoid this particular bug so we can get the tests working right now.

**Comment by plajjan** [comment]
I believe I've been able to work around this issue by writing the test applications differently, which is merged in with #518. Closing this.
